---
Documentation:
    Enabled: false

Metrics/LineLength:
  Max: 140

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 200

Style/TrivialAccessors:
  Enabled: false
Style/EachWithObject:
  Enabled: false